import Link from 'next/link'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dzckiLNH52H
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function Hero() {
  return (
    (<section
      className="w-full h-[89.9vh]  py-12 md:py-24 lg:py-32 xl:py-48 bg-gradient-to-r from-[#ff6b6b] to-[#ffa500]">
      <div
        className="container px-4 md:px-6 flex flex-col items-center justify-center text-center space-y-6">
        <div className="max-w-3xl space-y-4">
          <h1
            className="text-4xl font-bold tracking-tight text-primary-foreground sm:text-5xl lg:text-6xl">
            Discover the Magic of Movies, Dramas, and Books
          </h1>
          <p className="text-lg text-muted-foreground md:text-xl">
            Explore our vast collection of captivating stories and immerse yourself in the world of entertainment.
          </p>
        </div>
        <div className="flex gap-2">
          <Link href="/login" className=""><Button type="button" variant="default" className="bg-black text-white">Login</Button></Link>
          <Link href="/signup"><Button type="button" variant="default" className="bg-black text-white">Get Started</Button></Link>
        </div>
      </div>
    </section >)
  );
}
